"""empty message

Revision ID: d66b501d5233
Revises: a87abc758a5c
Create Date: 2022-01-08 15:04:30.154253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66b501d5233'
down_revision = 'a87abc758a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('order', 'orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('orders', 'order')
    # ### end Alembic commands ###
